### PR TITLE
Improve directories autocomplete performance

### PR DESCRIPTION
**Pull request by JoeNg93**
"glob" performance is really poor when in repositories with a lot of
files (e.g. monorepo). Change to "globby" will improve the performance considerably

### CODE REVIEW

**Comment by patbenatar** [comment]
@JoeNg93 thanks for this -- and sorry for my delay in reviewing it. This looks great! :shipit:

**Comment by patbenatar** [comment]
Released in 1.2.1

**Comment by patbenatar** [comment]
@JoeNg93 I had to revert this change because of https://github.com/patbenatar/vscode-advanced-new-file/issues/81

**Comment by JoeNg93** [comment]
Yes, thanks for doing that! I will try to reproduce in the meantime since it's been working great for several projects of mine.

**Comment by patbenatar** [comment]
Thanks @JoeNg93 !

**Pull request merged**
