### PR TITLE
Add a test that should fail on Windows

### PR DESCRIPTION
**Pull request by patbenatar**
@Kaffiend I'm not able to reproduce #27 on Mac, so I'm trying here to get a failing test case on Appveyor (Windows CI). Just pushed an initial attempt, if it doesn't fail on Windows I could use your help trying to get a failing test case setup.

### CODE REVIEW

**Comment by Kaffiend** [comment]
Ok, pulling it down now. 
* Full setup.
Windows 10 Enterprise x64
`Code.exe` added to path.
Code is installed on an OS Drive `C:\`
Projects on a ssd data drive `B:\`

I also have another drive with a Linux distro, i have not confirmed the same issue #27  there yet.

**Comment by Kaffiend** [comment]
Ok trying to run the tests but for some reason the test script is downloading the vscode instance into a subdirectory and it has to be manually moved.
image
`red` expected exe location
`yellow` actual downloaded location

**Comment by patbenatar** [comment]
@Kaffiend yeah, see https://github.com/Microsoft/vscode-extension-vscode/issues/64 and the recommended workaround https://github.com/Microsoft/vscode-extension-vscode/issues/64#issuecomment-308647323

That workaround worked for me on Appveyor

**Comment by Kaffiend** [comment]
all tests pass.

**Comment by patbenatar** [comment]
Hmm, I think this test should be reproducing the scenario mentioned in #27 ... There's a `out/test/dummy_project/` directory that the tests use to simulate a project directory tree. I created a `dev/` folder in there and then in the test case add `dev/` to the gitignore file, and it seems to be correctly ignored. What am I missing?

**Comment by Kaffiend** [comment]
i think its just prefixed `/` that is the issue.

**Comment by Kaffiend** [comment]
hmm disregard my last, derp. Maybe if its at the root of the project?
sketch

**Comment by Kaffiend** [comment]
something else i notice, the limit is 2 dirs deep and you can see in the fuzzy finder its traversing more than 2.

**Comment by patbenatar** [comment]
This is a minimal reproduction of `dev/` folder in the root of the project, using the contents of your gitignore:

screen shot 2017-07-05 at 4 57 58 pm

It doesn't show up in the picker on Mac. Does something like that work for you on Win?

Where is the limit set to 2 dirs deep?

**Comment by Kaffiend** [comment]
disregard the limit, i was running low on coffee and misunderstood [this](https://github.com/patbenatar/vscode-advanced-new-file/blob/master/src/extension.ts#L73)

**Comment by Kaffiend** [comment]
i just retested, prefixed `/` works as intended. No prefixed `/` but suffixed `/` does not.

**Comment by Kaffiend** [comment]
🤦‍♂️ it didn't dawn on me until i wrote that last comment out, and it somehow got my head on straight. Git ignore once i cleared cache exhibits the same behavior. Not sure why i was thinking otherwise.

**Comment by patbenatar** [comment]
Oops! Thanks for getting that sorted out.

**Pull request closed without merging**
